# Generated by Django 4.2.28 on 2026-07-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0121_alter_estimate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='network',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Secret'), (1, 'Private'), (2, 'Public')], default=2),
        ),
    ]
