# Generated by Django 4.2.30 on 2026-07-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0133_recurring'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_html', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='planned', max_length=30)),
                ('sort_order', models.FloatField(default=65535)),
                ('logo_props', models.JSONField(default=dict)),
                ('progress_snapshot', models.JSONField(default=dict)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Initiative',
                'verbose_name_plural': 'Initiatives',
                'db_table': 'initiatives',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='InitiativeEpic',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Initiative Epic',
                'verbose_name_plural': 'Initiative Epics',
                'db_table': 'initiative_epics',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InitiativeProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sort_order', models.FloatField(default=65535)),
            ],
            options={
                'verbose_name': 'Initiative Project',
                'verbose_name_plural': 'Initiative Projects',
                'db_table': 'initiative_projects',
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='initiativeproject',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='initiativeproject',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_projects', to='db.initiative'),
        ),
        migrations.AddField(
            model_name='initiativeproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_initiatives', to='db.project'),
        ),
        migrations.AddField(
            model_name='initiativeproject',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='initiativeproject',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_initiative_projects', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='initiativeepic',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='initiativeepic',
            name='epic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epic_initiatives', to='db.issue'),
        ),
        migrations.AddField(
            model_name='initiativeepic',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_epics', to='db.initiative'),
        ),
        migrations.AddField(
            model_name='initiativeepic',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='initiativeepic',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_initiative_epics', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='initiative',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_initiative', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='initiativeproject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('initiative', 'project'), name='initiative_project_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='initiativeproject',
            unique_together={('initiative', 'project', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='initiativeepic',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('initiative', 'epic'), name='initiative_epic_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='initiativeepic',
            unique_together={('initiative', 'epic', 'deleted_at')},
        ),
    ]
