# Generated by Django 4.2.30 on 2026-07-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0134_initiatives'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityUpdate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('on-track', 'On Track'), ('at-risk', 'At Risk'), ('off-track', 'Off Track')], default='on-track', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('description_html', models.JSONField(blank=True, null=True)),
                ('completed_percentage', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Update',
                'verbose_name_plural': 'Updates',
                'db_table': 'entity_updates',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='entityupdate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='entityupdate',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_updates', to='db.cycle'),
        ),
        migrations.AddField(
            model_name='entityupdate',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_updates', to='db.initiative'),
        ),
        migrations.AddField(
            model_name='entityupdate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_updates', to='db.project'),
        ),
        migrations.AddField(
            model_name='entityupdate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='entityupdate',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_updates', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='entityupdate',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('cycle__isnull', True), ('initiative__isnull', True), ('project__isnull', False)), models.Q(('cycle__isnull', False), ('initiative__isnull', True), ('project__isnull', True)), models.Q(('cycle__isnull', True), ('initiative__isnull', False), ('project__isnull', True)), _connector='OR'), name='entity_update_exactly_one_parent'),
        ),
    ]
