# Generated by Django 4.2.30 on 2026-07-08
# Project States (mote) — see docs/mote-design/04-planning-hierarchy.md section 3.
# Creates project_states, adds Project.state, and data-seeds the 6 default states
# per existing workspace (mirrors create_default_project_states), backfilling each
# project to its workspace's default state.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


# (name, color, sequence, group, default) — mirrors DEFAULT_PROJECT_STATES.
DEFAULTS = [
    ("Backlog", "#A3A3A3", 15000, "backlog", False),
    ("Planned", "#60646C", 25000, "planned", True),
    ("Execution", "#F59E0B", 35000, "execution", False),
    ("Monitoring", "#3B82F6", 45000, "monitoring", False),
    ("Completed", "#46A758", 55000, "completed", False),
    ("Cancelled", "#9AA4BC", 65000, "cancelled", False),
]


def seed_project_states(apps, schema_editor):
    ProjectState = apps.get_model("db", "ProjectState")
    Workspace = apps.get_model("db", "Workspace")
    Project = apps.get_model("db", "Project")
    for ws in Workspace.objects.all():
        if ProjectState.objects.filter(workspace_id=ws.id).exists():
            continue
        ProjectState.objects.bulk_create(
            [
                ProjectState(
                    workspace_id=ws.id, name=name, color=color,
                    sequence=seq, group=group, default=default,
                )
                for (name, color, seq, group, default) in DEFAULTS
            ]
        )
        default_ps = ProjectState.objects.filter(workspace_id=ws.id, default=True).first()
        if default_ps:
            Project.objects.filter(workspace_id=ws.id, state__isnull=True).update(state_id=default_ps.id)


def unseed_project_states(apps, schema_editor):
    # Non-destructive reverse: null out project.state; state rows go with the table.
    Project = apps.get_model("db", "Project")
    Project.objects.update(state=None)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0136_milestones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(max_length=255)),
                ('group', models.CharField(choices=[('backlog', 'Backlog'), ('planned', 'Planned'), ('execution', 'Execution'), ('monitoring', 'Monitoring'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('sequence', models.FloatField(default=65535)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Project State',
                'verbose_name_plural': 'Project States',
                'db_table': 'project_states',
                'ordering': ('sequence',),
            },
        ),
        migrations.AddField(
            model_name='projectstate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='projectstate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='projectstate',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_project_states', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='db.projectstate'),
        ),
        migrations.AlterUniqueTogether(
            name='projectstate',
            unique_together={('name', 'workspace', 'deleted_at')},
        ),
        migrations.RunPython(seed_project_states, unseed_project_states),
    ]
