# Generated by Django 4.2.30 on 2026-07-08 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0137_project_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCollection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('logo_props', models.JSONField(default=dict)),
                ('sort_order', models.FloatField(default=65535)),
                ('is_shared', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Page Collection',
                'verbose_name_plural': 'Page Collections',
                'db_table': 'page_collections',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='PageCollectionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sort_order', models.FloatField(default=65535)),
            ],
            options={
                'verbose_name': 'Page Collection Item',
                'verbose_name_plural': 'Page Collection Items',
                'db_table': 'page_collection_items',
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='pagecollectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db.pagecollection'),
        ),
        migrations.AddField(
            model_name='pagecollectionitem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pagecollectionitem',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='db.page'),
        ),
        migrations.AddField(
            model_name='pagecollectionitem',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pagecollectionitem',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_collection_items', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='owned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_collections', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='pagecollectionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('collection', 'page'), name='page_collection_item_unique_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='pagecollectionitem',
            unique_together={('collection', 'page', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='pagecollection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'workspace', 'owned_by'), name='page_collection_unique_name_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='pagecollection',
            unique_together={('name', 'workspace', 'owned_by', 'deleted_at')},
        ),
    ]
