# Generated by Django 4.2.30 on 2026-07-08 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0138_page_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCollaborator',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(5, 'VIEWER'), (15, 'MEMBER'), (20, 'ADMIN')], default=5)),
            ],
            options={
                'verbose_name': 'Page Collaborator',
                'verbose_name_plural': 'Page Collaborators',
                'db_table': 'page_collaborators',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='pagecollaborator',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pagecollaborator',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_pages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagecollaborator',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='db.page'),
        ),
        migrations.AddField(
            model_name='pagecollaborator',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pagecollaborator',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_collaborators', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='pagecollaborator',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('page', 'member'), name='page_collaborator_unique_page_member_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='pagecollaborator',
            unique_together={('page', 'member', 'deleted_at')},
        ),
    ]
